Provide default error message, as zipkin will throw exception for empty annotations
auxmoney/OpentracingBundle-core pull request #48
Opened 2020-11-06 16:42 UTC by dgafka

This PR provides an default error message, as zipkin integration does not allow for empty annotations.

2020-12-10 08:41 UTC, cawolf requested changes
I have added some minor feedback, but in general: LGTM!

2020-12-10 08:41 UTC, cawolf commented on EventListener/ExceptionLogSubscriber.php
> +                'message' => $exception->getMessage() ? $exception->getMessage() : self::DEFAULT_ERROR_MESSAGE,
This can be shortened to
```suggestion
                'message' => $exception->getMessage() ?: self::DEFAULT_ERROR_MESSAGE,
```

2020-12-10 08:41 UTC, cawolf commented on EventListener/ExceptionLogSubscriber.php
> +    const DEFAULT_ERROR_MESSAGE = "No error message given";
I think we should keep this constant private, as it is just a default message.

```suggestion
    private const DEFAULT_ERROR_MESSAGE = "No error message given";
```

2020-12-10 08:41 UTC, cawolf commented on Tests/EventListener/ExceptionLogSubscriberTest.php
> +            self::assertEquals(ExceptionLogSubscriber::DEFAULT_ERROR_MESSAGE, $argument['message']);
`ExceptionLogSubscriber::DEFAULT_ERROR_MESSAGE` won't be available here, if we change the `const` to `private const` there.

```suggestion
            self::assertEquals("No error message given", $argument['message']);
```

2020-12-10 11:43 UTC, dgafka commented
@cawolf Thanks for review :)

2020-12-15 14:39 UTC, cawolf approved these changes
LGTM!

2020-12-15 14:41 UTC, merged

2020-12-15 14:42 UTC, cawolf commented
:tada: This PR is included in version 0.7.5 :tada:

The release is available on [GitHub release](https://github.com/auxmoney/OpentracingBundle-core/releases/tag/v0.7.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: